version: "3"
services:
  collection-server:
    build:
      context: ../server/
      dockerfile: ../dev/server.Dockerfile
    restart: always
    volumes:
      - ../server:/go/src/github.com/mazrean/quauntainer
    environment:
      QUANTAINER_ENV: development
      FILE_PATH: ./uploads
      CLIENT_ID:
      CLIENT_SECRET:
      DB_USERNAME: root
      DB_PASSWORD: pass
      DB_HOSTNAME: mariadb
      DB_PORT: 3306
      DB_DATABASE: quantainer
      SESSION_SECRET: secret
      ADDR: :3000
    ports: 
      - 3000:3000
  mariadb:
    image: mariadb:10.5.2
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: quantainer
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ../../mysql/data:/var/lib/mysql
