// Package Openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package Openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	TraPMemberAuthScopes = "traPMemberAuth.Scopes"
)

// Defines values for FileType.
const (
	FileTypeGif FileType = "gif"

	FileTypeJpeg FileType = "jpeg"

	FileTypeOther FileType = "other"

	FileTypePng FileType = "png"

	FileTypeSvg FileType = "svg"

	FileTypeWebp FileType = "webp"
)

// ファイル
type File struct {
	// ファイル作成時刻
	CreatedAt time.Time `json:"createdAt"`

	// ファイルの作成者
	Creator string `json:"creator"`

	// ファイルのid
	Id string `json:"id"`

	// ファイルの種類
	Type FileType `json:"type"`
}

// ファイルの種類
type FileType string

// 新規ファイル
type NewFile struct {
	File string `json:"file"`
}

// ユーザー
type User struct {
	// traQのID（UUID）
	Id string `json:"id"`

	// traQID（UUIDでない方）
	Name string `json:"name"`
}

// FileIDInPath defines model for fileIDInPath.
type FileIDInPath string

// CallbackParams defines parameters for Callback.
type CallbackParams struct {
	// OAuth2.0のcode
	Code string `json:"code"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ファイルのアップロード
	// (POST /files)
	PostFile(ctx echo.Context) error
	// ファイルの取得
	// (GET /files/{fileID})
	GetFile(ctx echo.Context, fileID FileIDInPath) error
	// OAuthのコールバック
	// (GET /oauth2/callback)
	Callback(ctx echo.Context, params CallbackParams) error
	// OAuthのcode_challengeとかの取得
	// (GET /oauth2/generate/code)
	GetGeneratedCode(ctx echo.Context) error
	// ログアウト
	// (POST /oauth2/logout)
	PostLogout(ctx echo.Context) error
	// traQの全ユーザー取得
	// (GET /users)
	GetUsers(ctx echo.Context) error
	// 自分の情報の取得
	// (GET /users/me)
	GetMe(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostFile converts echo context to params.
func (w *ServerInterfaceWrapper) PostFile(ctx echo.Context) error {
	var err error

	ctx.Set(TraPMemberAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostFile(ctx)
	return err
}

// GetFile converts echo context to params.
func (w *ServerInterfaceWrapper) GetFile(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "fileID" -------------
	var fileID FileIDInPath

	err = runtime.BindStyledParameterWithLocation("simple", false, "fileID", runtime.ParamLocationPath, ctx.Param("fileID"), &fileID)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter fileID: %s", err))
	}

	ctx.Set(TraPMemberAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetFile(ctx, fileID)
	return err
}

// Callback converts echo context to params.
func (w *ServerInterfaceWrapper) Callback(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CallbackParams
	// ------------- Required query parameter "code" -------------

	err = runtime.BindQueryParameter("form", true, true, "code", ctx.QueryParams(), &params.Code)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter code: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Callback(ctx, params)
	return err
}

// GetGeneratedCode converts echo context to params.
func (w *ServerInterfaceWrapper) GetGeneratedCode(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetGeneratedCode(ctx)
	return err
}

// PostLogout converts echo context to params.
func (w *ServerInterfaceWrapper) PostLogout(ctx echo.Context) error {
	var err error

	ctx.Set(TraPMemberAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostLogout(ctx)
	return err
}

// GetUsers converts echo context to params.
func (w *ServerInterfaceWrapper) GetUsers(ctx echo.Context) error {
	var err error

	ctx.Set(TraPMemberAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetUsers(ctx)
	return err
}

// GetMe converts echo context to params.
func (w *ServerInterfaceWrapper) GetMe(ctx echo.Context) error {
	var err error

	ctx.Set(TraPMemberAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetMe(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/files", wrapper.PostFile)
	router.GET(baseURL+"/files/:fileID", wrapper.GetFile)
	router.GET(baseURL+"/oauth2/callback", wrapper.Callback)
	router.GET(baseURL+"/oauth2/generate/code", wrapper.GetGeneratedCode)
	router.POST(baseURL+"/oauth2/logout", wrapper.PostLogout)
	router.GET(baseURL+"/users", wrapper.GetUsers)
	router.GET(baseURL+"/users/me", wrapper.GetMe)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RYXW8TRxf+K2je9+5dZ9dOojdZxAUFlUYtJQhy0whV491je2B3Z5mZDaSRJdaG1i1F",
	"cNGCkGgpFIU0iECF1KqF9s8MNuGqf6Ga2bXXH2s7TYtUbkDrmfMxz/OcM2eygRzqhzSAQHBkb6AQM+yD",
	"AKa/KsSDpaNLwTIWNfXtAncYCQWhAbKRbH4tG/dk44FsPpLxztJRZCCiFkK13UAB9gHZqRNkIAbnI8LA",
	"RbZgERiIOzXwsY5DmY8FslEUERcZSKyHypILRoIqqtfr3c06q3eJB5OzQQYKGQ2BCQLaxGGABbiHxWS7",
	"l7/d6bRudG432q3nyEBwEfuhioVKVnGxYC0WSvOnrUV7vmjPFj9CRpa3iwUUBPFhNHkjCU7ZVACT6LuX",
	"rgyE9vEnDHCQ55i4U31qODNnUJ7DpYX/u4XivLtYmKsUS4WFSqVSKLvWwkK5WCrjBav/XPl8dH/YQP9l",
	"UEE2+o+ZqchMmTIVTafVPkVfxv0qylxm2Bh9FJ3pBaTls+AIFbDnbNqBX23tvL73rTp0EPkq2tkQqkoP",
	"gfr3ApRDZCC+pj6qpIIMREUNWF/M7JAfwoV8qXVuPt3dvD5RcJXUsIdkmQSYredoexAbbZcHwAqHXAVt",
	"yuYL2fhJNl+M5JAnD8HwSV2rf7xorayo/z5/IwJJaj8vei+0jB/KeFvGlzs3fxlOY6zo86SkY41ippoG",
	"OBEjYv2UkmQCimB4+Tj4ZWCHo6Sp6ZblUHqOQNa0OHBOaMCzDHBI3of1pBmRoEJ1W6GBwI5uKqldlnjE",
	"PGSjmhAht02zSkQtKs841DfTLebJCAcCkwCYAmwQqGxNxjuHl5dUGkRoaLKlA8nCGjCeWBVnrBlLOaMh",
	"BDgkyEazM9ZMSSkDi5o+v6kUlrR6ysXUcpKN+7LZlM1bsvlYKa2peFIiw2r/kotstEy50HWSUANcvEPd",
	"9S48EOggfuQJEmImTCWdgouFbvzZFTCpk3QLsV5P+OchDXhyiJJlDUXCYegRR6dnnuXqTHsN040xTEan",
	"daP9xV2F65xVzEPssWw81Yg9k/EtGW/K+HKibGUzn2Q4aPPy11bnzl29W+2TjS3Z/EHVcL9qkb06qtfV",
	"M/UzBuKR76t2sje+BK7yrLmoEIkKzI3kbq6rBKswXQ3t6zfbv98aUcAxyASwZ26oI0AUuGCA/UGO9tIz",
	"iY+rYOrevk9bdSHs01TfIvuz5aa6dfZry9eq/7voe2Psk1stZ3Z6e+XcE9yQhI2BQXU1v66zLebAIFtX",
	"9ibFkaiVTAd7Xhk758aWwAmVqK6sZ7qgHsnmDVVijScjdXCk6yu/EMbTkLPsUBdk/OXu9gMZf5+S0Lgq",
	"4y0ZX9snDz2QJx6pi3SCTx7WOfiUZiwZ76icu2+A8xFoLaf3Yro0/gkwLNt+jqoQKJjB1F6mEaU2fezU",
	"sOdBUAWN2NWJvetY6t490k2yj7tZa3Ycd/JSIx2ndrevta8/efXV89ff3Jfxo9fxz68ePpfxbcXYpQYy",
	"UA2wm76pToEoHEmmjYEyzoaf7uxxCJcdF4ql2bn5gweUcg+ZBw+8J0R4IvDy2kT9H5LFNABHFNJHlUer",
	"NBKTxouku9yXjU3ZbOUOEx8kPv5qEf0Le9nwWXORi3iqjFxVpwprX9nqn/XHi3lFe/ubUxIR4PNp45J+",
	"kdSz+ZgxvP7W3TdT4O0Spjjqp8v0x/eh3c+2261PZbzTaV5pf/fjxNZzHNAbHGgTht4yRibAN8yGds3W",
	"uvdS9uKyTdOjDvZqlAt71rIsE4fEXCsiFSr10nuypcVYN3q/RImyN/r/gqWmhj8DAAD//yggaTQtEwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
