version: "3"
services:
  client:
    image: ghcr.io/mazrean/quantainer-client:latest
    restart: always
    ports:
      - 80:80
      - 443:443
  server:
    image: ghcr.io/mazrean/quantainer-server:latest
    restart: always
    volumes:
      - /etc/quantainer/cache:/go/src/github.com/mazrean/quauntainer/cache
    environment:
      QUANTAINER_ENV: production
      FILE_PATH: ./cache
      OS_AUTH_URL:
      OS_USERNAME:
      OS_PASSWORD:
      OS_TENANT_ID:
      OS_TENANT_NAME:
      OS_CONTAINER:
      CLIENT_ID:
      CLIENT_SECRET:
      DB_USERNAME: quantainer
      DB_PASSWORD:
      DB_HOSTNAME: mariadb
      DB_PORT: 3306
      DB_DATABASE: quantainer
      SESSION_SECRET:
      ADDR: :3000
      ACCESS_TOKEN:
      VERIFICATION_TOKEN:
      DEFAULT_CHANNELS: 858ae414-21ec-40d8-be6a-012620db8edf
  mariadb:
    image: mariadb:10.5.2
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_PASSWORD:
      MYSQL_USER: quantainer
      MYSQL_DATABASE: quantainer
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - /etc/quantainer/mariadb/data:/var/lib/mysql
