name: Server CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  mod:
    name: Mod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.17
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.7
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gomod-
      - run: go mod download
        working-directory: ./server
  mockgen:
    name: MockGen
    runs-on: ubuntu-latest
    needs: [mod]
    steps:
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.17
      - uses: actions/checkout@v2
      - name: Add PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - run: go install github.com/golang/mock/mockgen
        working-directory: ./server
      - run: go generate ./...
        working-directory: ./server
      - uses: actions/upload-artifact@v1
        with:
          name: mockGenerated
          path: ./server
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [mockgen]
    env:
      GOCACHE: "/tmp/go/cache"
    steps:
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.17
      - uses: actions/download-artifact@v1
        with:
          name: mockGenerated
      - uses: actions/cache@v2.1.7
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gomod-
      - uses: actions/cache@v2.1.7
        with:
          path: /tmp/go/cache
          key: ${{ runner.os }}-go-build-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-go-build-${{ github.ref }}-
            ${{ runner.os }}-go-build-
      - run: go build -o collection
        working-directory: ./mockGenerated
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [mockgen]
    services:
      mysql:
        image: mariadb:10.6.4
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: quantainer
    steps:
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.17
      - uses: actions/download-artifact@v1
        with:
          name: mockGenerated
      - uses: actions/cache@v2.1.7
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gomod-
      - run: go test ./... -v -coverprofile=../coverage.txt -race -vet=off
        env:
          COLLECTION_ENV: production
          DB_USERNAME: root
          DB_PASSWORD: password
          DB_HOSTNAME: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: quantainer
        working-directory: ./mockGenerated
      - name: Upload coverage data
        uses: codecov/codecov-action@v2.1.0
        with:
          file: ./coverage.txt
          yml: ./codecov.yml
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: coverage.txt
          path: coverage.txt
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [mockgen]
    steps:
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.17
      - uses: actions/download-artifact@v1
        with:
          name: mockGenerated
      - uses: actions/cache@v2.1.7
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gomod-
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          reporter: github-pr-check
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workdir: mockGenerated
          fail_on_error: true
